<?php include __DIR__ . '/../layouts/app.phtml' ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>   
                    </tr>
                    <?php foreach ($urls as $url) : ?>
                        <tr>
                            <td><?= $url['id']?></th>
                            <td><a href="/urls/<?= $url['id']?>"><?= $url['name']?></a></th>
                            <td><?= $datesOfCheck[$url['id']]['created_at'] ?? null ?></th>
                            <td><?= $datesOfCheck[$url['id']]['status_code'] ?? null ?></th>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php include __DIR__ . '/../layouts/footer.phtml' ?>