<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    </header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md bg-dark bg-dark px-3">
            <a class="navbar-brand text-white" href="/">Анализатор страниц</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active text-white" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="flex-grow-1">
        <div class="container-lg">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1>Анализатор страниц</h1>
                <p>Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <input class="form-control form-control-lg" type="text" placeholder="https://www.example.com" name=url[name]>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </main>
    <footer class="border-top">
        <p class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </p>
    </footer>
</body>
</html>