<?php include 'layouts/app.phtml' ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
    <h1></h1>
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
            <form action="/urls" method="post" class="row mb-3" required="">
                <div class="col-8">
                        <?php if (isset($errors['name'][0]) && $errors['name'][0] === "URL не должен быть пустым"): ?>
                            <input class="form-control form-control-lg is-invalid" type="text" placeholder="https://www.example.com" name=url[name]>
                            <div class="invalid-feedback d-block">
                            <?= $errors['name'][0]?>
                            </div>
                        <?php elseif(isset($errors['name'][0]) && $errors['name'][0] !== "URL не должен быть пустым") :?>
                            <input class="form-control form-control-lg is-invalid" type="text" placeholder="https://www.example.com" value=<?= $url['name']?>>
                            <div class="invalid-feedback d-block">
                            <?= $errors['name'][0]?>
                            </div>
                        <?php else :?>
                            <input class="form-control form-control-lg" type="text" placeholder="https://www.example.com" name=url[name]>
                        <?php endif ?>
                </div>
                <div class="col-2">
                    <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                </div>
            </form>
        </div>
    </div>
</main>

<?php include 'layouts/footer.phtml' ?>

